# Generated by Django 3.2.8 on 2021-10-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20211027_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='description',
            field=models.TextField(),
        ),
    ]
