# Generated by Django 3.2.8 on 2021-10-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_commodity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='description',
            field=models.TextField(default='This is a description'),
        ),
    ]
