# Generated by Django 3.2.8 on 2021-10-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_commodity_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
