# Generated by Django 3.2.8 on 2021-10-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_commodity_is_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'ordering': ['id'], 'verbose_name_plural': 'Commodity'},
        ),
    ]
