# Generated by Django 3.2.8 on 2021-11-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
