# Generated by Django 3.2.8 on 2021-11-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_alter_commodity_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
